### PR TITLE
Fix the `base_format` list.

### LINKED ISSUE #346: time schema is inconsistent with asdf-astropy
This has been hidden by and is related to https://github.com/asdf-format/asdf-standard/issues/345

asdf-astropy serializes astropy.time.Time values in a way that is inconsistent with the time schema. One example is that the schema lists [allowed base_formats](https://github.com/asdf-format/asdf-standard/blob/master/resources/schemas/stsci.edu/asdf/time/time-1.2.0.yaml#L180):
```yaml
    enum:
      - iso
      - yday
      - byear
      - jyear
      - decimalyear
      - jd
      - mjd
      - gps
      - unix
      - cxcsec
```
which are incomplete compared to the base_format values [produced by asdf-astropy](https://github.com/astropy/asdf-astropy/blob/main/asdf_astropy/converters/time/time.py#L22) (which can contain any astropy.time.Time format). For example, serializing
```python
astropy.time.Time(730120.0003703703, format="plot_date")
```
produces

```yaml
t: !time/time-1.1.0 {base_format: plot_date, value: '2000-01-01T00:00:32.000'}
```

Given the assumed intended behavior of base_format (to store the astropy.time.Time format) this looks more like a schema bug than an issue with the asdf-astropy implementation.

The base_format is one (but possibly not the only) error with the time schema that was hidden by the ndarray schema issue.

### LINKED ISSUE #352: Time schema validates arbitrary ndarray objects that converters cannot interpret as time
Neither the converter in astropy or asdf-astropy supports the reference to the ndarray object, I vote for removing the reference:
https://github.com/asdf-format/asdf-standard/blob/ecdf2648b75fc99053fa33a5ff06cab1561af5eb/resources/schemas/stsci.edu/asdf/time/time-1.2.0.yaml#L197
For example, the following is valid yaml if the ndarray reference is kept:
```yaml
!time/time-1.1.0
  data: [1, 2, 3]
```
So this validates during reading, but fails during conversion to astropy.Time.

### PR DESCRIPTION
**Pull request by WilliamJamieson**
Fixes #346.
Fixes #352 per comment https://github.com/asdf-format/asdf-standard/issues/352#issuecomment-1323770906

### CODE REVIEW

**Comment by braingram** [comment]
@perrygreenfield  Should this be an new time schema version (1.3)?

Also, @eslavich should we remove the ref to ndarray? If we leave it in the object definition changed here will never be used for validation because of issue https://github.com/asdf-format/asdf-standard/issues/345

**Comment by WilliamJamieson** [comment]
> @perrygreenfield Should this be an new time schema version (1.3)?
> 
> Also, @eslavich should we remove the ref to ndarray? If we leave it in the object definition changed here will never be used for validation because of issue #345

This should be time-1.2.0 as these are simply corrections to the changes that brought `1.2.0` into existence

**Comment by braingram** [comment]
Perhaps this is a separate issue but time is referenced in wcs (one example [here](https://github.com/asdf-format/asdf-standard/blob/master/resources/schemas/stsci.edu/asdf/wcs/frame-1.1.0.yaml#L98) I'm only seeing 2 refs). The refs are currently pointing to time-1.1. Should these be updated to time-1.2?

**Comment by WilliamJamieson** [comment]
> Perhaps this is a separate issue but time is referenced in wcs (one example [here](https://github.com/asdf-format/asdf-standard/blob/master/resources/schemas/stsci.edu/asdf/wcs/frame-1.1.0.yaml?rgh-link-date=2022-11-17T20%3A53%3A26Z#L98) I'm only seeing 2 refs). The refs are currently pointing to time-1.1. Should these be updated to time-1.2?

Since `additionalProperties` is not set and its default is `true` then the `base_format` will field will not cause any issues in wcs. When asdf-standard 1.6 is finalized and becomes the stable version then we should update things.

**Comment by braingram** [comment]
Given that neither the converter in astropy or asdf-astropy supports the reference to the ndarray object, I vote for removing the reference:
https://github.com/asdf-format/asdf-standard/blob/ecdf2648b75fc99053fa33a5ff06cab1561af5eb/resources/schemas/stsci.edu/asdf/time/time-1.2.0.yaml#L197
For example, the following is valid if the ndarray reference is kept:
```yaml
!time/time-1.1.0
  data: [1, 2, 3]
```
However this fails to convert to a time.

**Comment by WilliamJamieson** [comment]
> Given that neither the converter in astropy or asdf-astropy supports the reference to the ndarray object, I vote for removing the reference:
> 
> https://github.com/asdf-format/asdf-standard/blob/ecdf2648b75fc99053fa33a5ff06cab1561af5eb/resources/schemas/stsci.edu/asdf/time/time-1.2.0.yaml#L197

This discussion is outside the scope of this PR. It is being removed in #350 and therefore should be discussed there.

**Comment by braingram** [comment]
I think the ndarray ref is relevant to this issue as it's an inconsistency between the schema and converters. https://github.com/asdf-format/asdf-standard/issues/346

This PR fixes the base_format errors but not 346 as the schema and converters are still inconsistent.

I'd be ok with merging this PR and reopening the issue.

**Comment by WilliamJamieson** [comment]
> This PR fixes the base_format errors but not 346 as the schema and converters are still inconsistent.

Please elaborate, what inconsistencies still exist?

**Review by braingram — COMMENTED** [review]
I see your point that separating the ndarray ref will make this easier to sort out. This looks good to me and I will open a new issue for the ndarray ref.

**Review by braingram — APPROVED** [review]
I'm not sure my previous comment was marked with approval. This looks great to me.

**Pull request merged**
